### ISSUE TITLE
Usage command

### ISSUE THREAD

**Issue by twhyntie** [calhewitt/lucid-frame-viewer#1]
Hi @calhewitt, 

This is amazing! Congratulations on developing this fantastic tool.

I've got it to work on my system (Xubuntu 14.04 VM) - the only thing I needed to do was:

``` bash
$ chmod a+x frameviewer    # to make the program executable
$ ./frameviewer [filename] # to run the program
```

So the `README.md` file might need updating.

Brilliant work, thanks! @twhyntie

**Comment by calhewitt** [comment]
Hello, thanks very much - glad you got it working! I have fixed the README - forgot that git didn't keep the execute permissions when files are cloned.

Thanks, @calhewitt

**Comment by twhyntie** [comment]
Brilliant, thanks!
